# Generated by Django 5.2.7 on 2025-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.TextField(max_length=200)),
                ('members', models.ManyToManyField(blank=True, related_name='courses', to='members_app.member')),
            ],
        ),
    ]
